"use client";
import Image from "next/image";
import Link from "next/link";
import { Heart, MessageCircle, Play, Plus, Star } from "lucide-react";
import { activities, allMedia, books, games, mediaById, movies, reviews, series } from "@/data/media";
import { MediaShelf, mediaHref } from "@/components/media/media-card";

const continueItems=[{media:series[2],label:"S05 E08 · Emancipation",progress:64,detail:"28 of 44 min"},{media:games[0],label:"Playing on PC",progress:45,detail:"27h 14m played"},{media:books[0],label:"Reading",progress:42,detail:"251 / 604 pages"}];
const activityVerb={rated_movie:"rated",completed_game:"completed",reviewed_media:"reviewed",watched_episode:"watched",updated_book_progress:"updated",created_list:"created"} as const;

export function HomePage(){const featured=movies[0];return <>
  <section className="hero"><div className="hero-bg"><Image src={featured.backdropUrl!} alt="Sweeping cinematic desert landscape" fill priority sizes="100vw"/></div><div className="hero-content"><div className="hero-kicker"><span className="pulse"/>Trending this week</div><h1>{featured.title}</h1><div className="hero-meta"><span>{featured.releaseYear}</span><span>·</span><span>{featured.runtime} min</span><span>·</span><span>{featured.genres.join(" / ")}</span><span className="rating">★ {featured.averageRating}</span></div><p className="hero-copy">{featured.description}</p><div className="actions"><Link className="button primary" href={mediaHref(featured)}><Play size={16} fill="currentColor"/>View story</Link><button className="button"><Plus size={17}/>Add</button><button className="button ghost"><Star size={16}/>Log / Rate</button></div></div></section>
  <div className="home-content"><section className="section" style={{marginTop:8}}><div className="section-head"><div><span className="eyebrow">In progress</span><h2>Continue your stories</h2></div><Link className="text-link" href="/library">Open library →</Link></div><div className="continue-grid">{continueItems.map(item=><Link className="continue-card" href={mediaHref(item.media)} key={item.media.id}><Image src={item.media.backdropUrl??item.media.posterUrl} alt="" fill sizes="(max-width:820px) 100vw, 33vw"/><div className="continue-body"><span className="type-badge">{item.media.mediaType==="tv"?"Series":item.media.mediaType}</span><h3>{item.media.title}</h3><span className="muted" style={{fontSize:12}}>{item.label}</span><div className="progress-track"><div className="progress-bar" style={{width:`${item.progress}%`}}/></div><div className="progress-meta"><span>{item.detail}</span><span>{item.progress}%</span></div></div></Link>)}</div></section>
  <section className="section"><div className="section-head"><div><span className="eyebrow">Across every medium</span><h2>Trending now</h2></div><Link className="text-link" href="/discover">Explore all →</Link></div><MediaShelf items={[movies[1],series[0],games[1],books[0],series[3],movies[2],games[2],books[3]]} showType/></section>
  <section className="section"><div className="section-head"><div><span className="eyebrow">Your circle</span><h2>From friends</h2></div></div><div className="feed-grid"><div className="panel">{activities.map(a=><div className="activity-row" key={a.id}><Image className="avatar" src={a.user.avatarUrl} alt="" width={42} height={42}/><div className="activity-copy"><strong>{a.user.displayName}</strong> {activityVerb[a.kind]}<br/><strong>{a.media?.title}</strong> {a.rating&&<span className="rating"> ★ {a.rating}</span>}{a.excerpt&&<><br/><span>“{a.excerpt}”</span></>}</div><span className="activity-time">{a.createdAt}</span></div>)}</div><div className="panel">{reviews.slice(0,2).map(review=>{const media=mediaById(review.mediaId)!;return <article className="review-card" key={review.id}><Link className="review-cover" href={mediaHref(media)}><Image src={media.posterUrl} alt="" fill sizes="88px"/></Link><div><div className="review-user"><Image className="avatar" src={review.user.avatarUrl} alt="" width={26} height={26}/><strong>{review.user.displayName}</strong><span className="rating">★ {review.rating}</span></div><p>{review.body}</p><div className="review-stats"><span><Heart size={12}/> {review.likes}</span><span><MessageCircle size={12}/> {review.comments}</span></div></div></article>})}</div></div></section>
  {[["Trending movies",movies],["Series everyone’s talking about",series],["Games worth getting lost in",games],["Books to keep close",books]].map(([title,items])=><section className="section" key={title as string}><div className="section-head"><h2>{title as string}</h2></div><MediaShelf items={items as typeof allMedia}/></section>)}
  <section className="section"><div className="section-head"><div><span className="eyebrow">On the horizon</span><h2>Recently released & coming soon</h2><p>Save a title and we’ll keep it on your radar.</p></div></div><MediaShelf items={[games[1],games[2],series[3],movies[0],books[3]]} showType/></section></div></>}
